version: '3.3'

services:
  db:
    image: mysql:9.4
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    volumes:
      - ~/softlinks/mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  dev:
    depends_on:
      - db
    image: rapporteket/norgast-dev:weekly
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - ~/GIT/norgast:/home/rstudio/norgast
      - ~/softlinks/mydata:/home/rstudio/mydata
      - config:/home/rstudio/rap_config
    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      USERID: $USERID
      PASSWORD: password
      DB_HOST: db
      DB_USER: root
      DB_PASS: root

  app:
    depends_on:
      - dev
    image: rapporteket/norgast
    volumes:
      - config:/app/R
    ports:
      - "3008:3838"
    restart: "no"
    environment:
      R_RAP_CONFIG_PATH: /app/R
      R_RAP_INSTANCE: DEV
        #      USERFULLNAME: Tore Tester Container
        #      SHINYPROXY_USERNAME: ttesterc
        #      SHINYPROXY_USERGROUPS: "LC,LC,SC,LC"
        #      USERORGID: "[1, 2, 3, 4]"
        #      USEREMAIL: ttesterc@holigong.no
  
  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080

volumes:
  config:
